framework:
    messenger:
        default_bus: command.bus
        failure_transport: failed
        buses:
            command.bus:
                middleware:
                    - App\Messenger\AuditMiddleware
            event.bus:
                default_middleware: allow_no_handlers

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#             sync: 'sync://'
             async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#                amqp options
                options:
                    exchange:
                        name: messages_priority_high
                    queues:
                        message_high: ~
             external_messages:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                 serializer: App\Messenger\ExternalJsonMessengerSerializer
                 options:
                     auto_setups: false
                     queues:
                        messages_from_external: ~


             failed: 'doctrine://default?queue_name=failed'


        routing:
            # Route your messages to the transports
             'App\Message\WelcomeUser': async_priority_high
