framework:
    messenger:
#        transports:
#            async:
#                dsn: 'sync://'
#                options: []
#            async_priority_high:
#                dsn: 'sync://'
#                options: []