# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(SITE_BASE_URL): '%env(SITE_BASE_SCHEME)%://%env(SITE_BASE_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Psr\Log\LoggerInterface $messengerAuditLogger: '@monolog.logger.messenger_audit'
            $uploadPaths: '%kernel.project_dir%/public/uploads'
    App\Twig\DaysLeftExtension:
        tags: [ 'twig.extension' ]
    App\EventListener\EventSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\MessageHandler\Command\:
        resource: '../src/MessageHandler/Command'
        autoconfigure: false
        tags: [{ name: messenger.message_handler, bus: command.bus }]

#    App\MessageHandler\Event\:
#        resource: '../src/MessageHandler/Event'
#        autoconfigure: false
#        tags: [{ name: messenger.message_handler, bus: event.bus }]
#
#    App\MessageHandler\Query\:
#        resource: '../src/MessageHandler/Query'
#        autoconfigure: false
#        tags: [ { name: messenger.message_handler, bus: query.bus } ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
